import type { AllocationCategory, Disclosure } from "./constants.ts";
import type { NullifierSchemeName } from "./nullifiers.ts";

export type { Disclosure } from "./constants.ts";

export interface WalletInput {
  /** "evm" or "solana". Serialized from the ChainConfig.family. */
  family: "evm" | "solana";
  /** EVM chain id, or 0 for Solana. When family==="evm" and chainId===0, the
   *  enclave discovers balances on every supported EVM chain for this address. */
  chainId: number;
  address: string;
  /** For EVM wallets the hex ECDSA signature over the ownership challenge.
   *  For Solana the base58 ed25519 signature over the same challenge bytes. */
  signature: string;
}

export interface RegistrationRequest {
  /** Anti-replay value, also returned in the attestation token nonces. */
  nonce: string;
  /** Unix ms the request was assembled. Enclave enforces a freshness window. */
  timestamp: number;
  /** The wallet set to enroll (the new account membership). */
  wallets: WalletInput[];
  /** Wallets to detach. Each must sign `walletRemovalChallenge` for this transition. */
  removals?: WalletInput[];
  /** How much portfolio detail the signed result may carry. */
  disclosure: Disclosure;
}

/** The inner plaintext that the client encrypts to the enclave. */
export interface EnvelopePayload {
  request: RegistrationRequest;
}

export interface SignedEnvelope {
  v: 1;
  /** base64url ephemeral X25519 public key generated by the client. */
  epk: string;
  /** base64url 12-byte AES-GCM nonce. */
  iv: string;
  /** base64url AES-256-GCM ciphertext (includes the 16-byte tag). */
  ct: string;
}

export interface AllocationEntry {
  category: AllocationCategory;
  /** Share of total portfolio in basis points (0..10000). */
  bps: number;
}

export interface WalletNullifierEntry {
  /** SHA-256(family || normalized address), hex. One-way. */
  walletNullifier: string;
  family: "evm" | "solana";
  chainId: number;
}

/**
 * The signed result body. It deliberately contains no address and no balance.
 * `allocation` and `walletNullifiers` are only populated when disclosure permits.
 */
export interface RegistrationResultBody {
  v: 1;
  policyVersion: string;
  tier: number;
  tierLabel: string;
  /** Lower bound of the assigned tier, micro-USD. */
  tierFloorMicroUsd: string;
  /** Lower bound of the next tier, micro-USD (0 for the top tier / none). */
  nextTierFloorMicroUsd: string;
  /** Coarse portfolio band, e.g. "<100k" | "100k-300k" | ... Never exact. */
  portfolioBand: string;
  /** Basis points of portfolio in stablecoins, always disclosed (safe). */
  stableBps: number;
  disclosure: Disclosure;
  allocation: AllocationEntry[];
  /** The enrolled wallet set after this transition. */
  walletNullifiers: WalletNullifierEntry[];
  /** Wallet nullifiers detached by this transition, when removals were requested. */
  removedWalletNullifiers?: WalletNullifierEntry[];
  /** Nullifier scheme the wallet nullifiers above were derived under. */
  nullifierScheme: NullifierSchemeName;
  identityNullifier: string;
  createdAt: number;
  expiresAt: number;
  /** Echo of the client nonce for binding. */
  nonce: string;
}

export interface EnclaveKeyAttestation {
  v: 1;
  keyAlgorithm: string;
  publicKey: string;
  createdAt: number;
  /** base64url attestation token from the Confidential Space launcher. */
  attestationToken: string;
  /** SHA-256 of signingPubkey || encryptionPubkey; must equal the token nonce. */
  keyNonce: string;
  provider: "confidential-space" | "mock";
  projectId: string;
  zone: string;
  keyId: string;
}

export interface SignedRegistration {
  v: 1;
  body: RegistrationResultBody;
  /** base64url Ed25519 signature over canonicalJson(body), by the enclave key. */
  signature: string;
  /** base64url Ed25519 public key the signature verifies against. */
  enclavePublicKey: string;
  /** base64url SHA-256 of the enclave public key. */
  keyId: string;
  /** Fresh attestation token; its nonce is the hash of the response payload. */
  attestationToken: string;
  provider: "confidential-space" | "mock";
}

export interface EnclaveHello {
  v: 1;
  name: "6figs-enclave";
  policyVersion: string;
  provider: "confidential-space" | "mock";
  encryptionPublicKey: string;
  /** Nullifier scheme the enclave derives wallet nullifiers under. */
  nullifierScheme: NullifierSchemeName;
  keyId: string;
  projectId: string;
  zone: string;
  createdAt: number;
  attestation: EnclaveKeyAttestation;
}

/** Plaintext HTTP error body from the enclave. */
export interface ErrorResponse {
  error: string;
  message: string;
}